/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package censo.views;

import censo.modelos.ModeloConductor;
import javax.swing.table.TableModel;

/**
 *
 * @author Admin
 */
public class Conductor extends javax.swing.JPanel {

    /**
     * Creates new form Conductor
     */
    public Conductor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Conductores Autorizados");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N.I.T", "Nombre", "Apellido", "N° de documento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void setData(javax.swing.table.DefaultTableModel data){
        jTable1.setModel(data);
    }
    
    public ModeloConductor[] getConductores(){
        ModeloConductor[] MCA = new ModeloConductor[5];
        
        TableModel tableModel = jTable1.getModel();
        int cols = tableModel.getColumnCount();
        int fils = tableModel.getRowCount();

        for(int i=0; i<fils; i++) {
            MCA[i] = new ModeloConductor();
            if(tableModel.getValueAt(i,2) != null){
                MCA[i].setApe1Con(tableModel.getValueAt(i,2).toString().split(" ")[0]);
                try{
                    MCA[i].setApe2Con(tableModel.getValueAt(i,2).toString().split(" ")[1]);
                }catch(Exception e){
                    System.out.println("el conductor " + tableModel.getValueAt(i,2).toString().split(" ")[0] +
                            " no tiene segundo nombre");
                }
            }
            if(tableModel.getValueAt(i,1) != null){
                MCA[i].setNomCon(tableModel.getValueAt(i,1).toString());
            }
            if(tableModel.getValueAt(i,3) != null){
                MCA[i].setIdConductor(Long.parseLong(tableModel.getValueAt(i,3).toString()));
            }
            if(tableModel.getValueAt(i,0) != null){
                MCA[i].setNit(tableModel.getValueAt(i,0).toString());
            }
        }
        return MCA;
    }
    
    public void setConductores(ModeloConductor[] MC){
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {MC[0].getNit(), MC[0].getNomCon(), MC[0].getApe1Con()+" "+MC[0].getApe2Con(), MC[0].getIdConductor()},
                {MC[1].getNit(), MC[1].getNomCon(), MC[1].getApe1Con()+" "+MC[1].getApe2Con(), MC[1].getIdConductor()},
                {MC[2].getNit(), MC[2].getNomCon(), MC[2].getApe1Con()+" "+MC[2].getApe2Con(), MC[2].getIdConductor()},
                {MC[3].getNit(), MC[3].getNomCon(), MC[3].getApe1Con()+" "+MC[3].getApe2Con(), MC[3].getIdConductor()},
                {MC[4].getNit(), MC[4].getNomCon(), MC[4].getApe1Con()+" "+MC[4].getApe2Con(), MC[4].getIdConductor()}
            },
            new String [] {
                "N.I.T", "Nombre", "Apellido", "N° de documento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
