/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package censo.views;

import censo.controladores.ControladorCenso;
import censo.controladores.ControladorImagen;
import censo.controladores.ControladorPersona;
import censo.modelos.ModeloCenso;
import censo.modelos.ModeloImagen;
import censo.modelos.ModeloPersona;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author GESTIONSAS
 */
public class RegistroFoto extends javax.swing.JPanel {

    /**
     * Creates new form Inicial
     */
    public RegistroFoto() {
        //inicializamos los componentes del panel
        initComponents();
        
        //creamos la camara y le damos tamaño y posicion
        camara = new Camara();
        camara.setLocation(5, 5);
        camara.setSize(224, 224);
        
        SelectCenso();
        
        ActualizaFecha();
        
        PanelCamara.add(camara);//agregamos la camara al panel en donde ira
        
        setVisible(true);//acemos que todos los elemtos sean vicibles
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ape1_pro = new javax.swing.JTextField();
        ape2_pro = new javax.swing.JTextField();
        nom_pro = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tipo_id = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        tipo_de_documento = new javax.swing.JComboBox<>();
        PanelCamara = new javax.swing.JPanel();
        tipo_de_persona = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        fecha_censo = new javax.swing.JLabel();
        n_censo = new javax.swing.JLabel();

        jLabel1.setText("N° Censo");

        jLabel2.setText("Fecha Censo");

        ape1_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ape1_proActionPerformed(evt);
            }
        });

        jLabel22.setText("Tipo Id");

        jLabel7.setText("N° De Identificacion");

        tipo_id.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel3.setText("Primer Apellido");

        jLabel4.setText("Segundo Apellido");

        jLabel5.setText("Nombres");

        tipo_de_documento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C.C", "T.I", "Contraseña", "Cedula Extrangera", "Libreta Militar" }));

        javax.swing.GroupLayout PanelCamaraLayout = new javax.swing.GroupLayout(PanelCamara);
        PanelCamara.setLayout(PanelCamaraLayout);
        PanelCamaraLayout.setHorizontalGroup(
            PanelCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelCamaraLayout.setVerticalGroup(
            PanelCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );

        tipo_de_persona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Propietario", "Poseedor" }));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        fecha_censo.setText("yyyy-mm-dd");

        n_censo.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(ape2_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(nom_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tipo_de_documento, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                .addComponent(tipo_id, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ape1_pro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(PanelCamara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(n_censo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fecha_censo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(tipo_de_persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(n_censo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tipo_de_persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha_censo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipo_de_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(tipo_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(ape1_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(ape2_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(nom_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelCamara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void ActualizaFecha(){
        //obtenemos fecha del equipo
        Calendar calendario = Calendar.getInstance();
        //mostrammos la fecha
        fecha_censo.setText(String.valueOf(calendario.get(Calendar.YEAR)) + "-" +
                String.valueOf(calendario.get(Calendar.MONTH)) + "-" +
                String.valueOf(calendario.get(Calendar.DAY_OF_MONTH)));
    }
    
    public void SelectCenso(){
        //las sigientes tres lineas nos diran el ultimo numero de censo ingresado
        ModeloCenso MC = new ModeloCenso();
        ControladorCenso CC = new ControladorCenso(MC);
        MC = CC.Select("SelectUltimo");
        
        //colocamos el numero de censo en pantalla
        n_censo.setText(String.valueOf(MC.getNCenso()+1));
    }
    
    public void Borrar(){
        ape1_pro.setText("");
        ape2_pro.setText("");
        nom_pro.setText("");
        tipo_id.setText("");
    }
    
    private void ape1_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ape1_proActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ape1_proActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Integer.parseInt(tipo_id.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "N° de documento no valido", "¡¡¡ERROR!!!", JOptionPane.ERROR_MESSAGE);
            tipo_id.setText("");
        }
        if(!ape1_pro.getText().equals("") &
                !ape2_pro.getText().equals("") &&
                !nom_pro.getText().equals("") &&
                !String.valueOf(tipo_de_documento.getSelectedItem()).equals("") &&
                !tipo_id.getText().equals("")){
            int _n_censo = 3;
            while(_n_censo == 3){
                ModeloCenso MC = new ModeloCenso();
                MC.setNCenso(Integer.parseInt(n_censo.getText()));
                
                ControladorCenso CC = new ControladorCenso(MC);
                _n_censo = CC.InsertarActualizar("InsertInicial");
                
                n_censo.setText(String.valueOf(Integer.parseInt(n_censo.getText()) + 1));
            }
            
            ModeloImagen MI = new ModeloImagen();
            MI.setNCenso(Integer.parseInt(n_censo.getText()));
            MI.setNombre(nom_pro.getText() + " " + ape1_pro.getText() + " " + ape2_pro.getText());
            MI.setImagen(camara.GetImagenBytea());
            
            ControladorImagen CI = new ControladorImagen(MI);
            CI.InsertarActualizar("InsertInicial");
            
            if(tipo_de_persona.getSelectedIndex() == 0){
                ModeloPersona MP = new ModeloPersona();
                MP.setIdPersona(Integer.parseInt(n_censo.getText()));
                MP.setApellido1(ape1_pro.getText());
                MP.setApellido2(ape2_pro.getText());
                MP.setNombre(nom_pro.getText());
                MP.setTipoDocumento(String.valueOf(tipo_de_documento.getSelectedItem()));
                MP.setNumeroDeDocumento(Integer.parseInt(tipo_id.getText()));
                
                ControladorPersona CP = new ControladorPersona(MP);
                CP.InsertarActualizar("InsertInicial");
                
            }else if(tipo_de_persona.getSelectedIndex() == 1){
                ModeloPersona MP = new ModeloPersona();
                MP.setIdPersona(Integer.parseInt(n_censo.getText()));
                MP.setApellido1(ape1_pro.getText());
                MP.setApellido2(ape2_pro.getText());
                MP.setNombre(nom_pro.getText());
                MP.setTipoDocumento(String.valueOf(tipo_de_documento.getSelectedItem()));
                MP.setNumeroDeDocumento(Integer.parseInt(tipo_id.getText()));
                
                ControladorPersona CP = new ControladorPersona(MP);
                CP.InsertarActualizar("InsertInicial");
                
            }
            JOptionPane.showMessageDialog(null, "censo n°:" + n_censo.getText() + "\n el registro a sido exitoso");
        }
        Borrar();
        SelectCenso();
        ActualizaFecha();
    }//GEN-LAST:event_jButton1ActionPerformed

    private Camara camara;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCamara;
    private javax.swing.JTextField ape1_pro;
    private javax.swing.JTextField ape2_pro;
    private javax.swing.JLabel fecha_censo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel n_censo;
    private javax.swing.JTextField nom_pro;
    private javax.swing.JComboBox<String> tipo_de_documento;
    private javax.swing.JComboBox<String> tipo_de_persona;
    private javax.swing.JFormattedTextField tipo_id;
    // End of variables declaration//GEN-END:variables
}
