/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package censo.views;

import censo.modelos.ModeloVeiculo;

/**
 *
 * @author GESTIONSAS
 */
public class Vehiculos extends javax.swing.JPanel {

    /**
     * Creates new form Vehiculos
     */
    public Vehiculos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel24 = new javax.swing.JLabel();
        soat = new javax.swing.ButtonGroup();
        tecno = new javax.swing.ButtonGroup();
        extracontactual = new javax.swing.ButtonGroup();
        n_chasis = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        n_licencia = new javax.swing.JTextField();
        modelo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cilindraje = new javax.swing.JTextField();
        o_transito = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        v_pago = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        linea = new javax.swing.JTextField();
        n_censo = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacion = new javax.swing.JTextArea();
        n_motor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fecha_censo = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        placa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fecha_de_pago = new javax.swing.JTextField();
        clase = new javax.swing.JComboBox<>();
        n_recibo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        servicio = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        soat1 = new javax.swing.JRadioButton();
        soat2 = new javax.swing.JRadioButton();
        tecno1 = new javax.swing.JRadioButton();
        tecno2 = new javax.swing.JRadioButton();
        extracontractual1 = new javax.swing.JRadioButton();
        extracontractual2 = new javax.swing.JRadioButton();
        uso_vehiculo = new javax.swing.JComboBox<>();

        jLabel24.setText("jLabel24");

        jLabel18.setText("N° Licencia");

        jLabel8.setText("Cilindraje");

        jLabel19.setText("Organismo de Transito");

        jLabel9.setText("Colores");

        jLabel20.setText("Extracontactual");

        jLabel10.setText("Marcas");

        jLabel21.setText("Valor Pagado");

        jLabel11.setText("Línea");

        jLabel12.setText("N° de Motor");

        jLabel22.setText("Uso Vehiculo");

        jLabel1.setText("N° Censo");

        n_censo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        n_censo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel2.setText("Fecha Censo");

        jLabel23.setText("Observaciones");

        observacion.setColumns(20);
        observacion.setRows(5);
        jScrollPane1.setViewportView(observacion);

        jLabel13.setText("S.O.A.T");

        fecha_censo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MM/yyyy"))));

        jLabel14.setText("Tecno");

        jLabel15.setText("Fecha de Pago");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DATOS DEL VEHICULO");

        jLabel16.setText("N° de Recibo");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("PLACA");

        placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placaActionPerformed(evt);
            }
        });

        jLabel5.setText("Clase de Vehiculo");

        clase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOTOXICLETA", "CARROS", "BUSETAS", "CAMIONES" }));

        jLabel6.setText("Tipo de Servicio");

        jLabel17.setText("N° de Chasis");

        servicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PARTICULAR", "PUPLICO", "DIPLOMATICO", "CARGA" }));
        servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicioActionPerformed(evt);
            }
        });

        jLabel7.setText("Modelo");

        soat.add(soat1);
        soat1.setText("SI");

        soat.add(soat2);
        soat2.setText("NO");

        tecno.add(tecno1);
        tecno1.setText("SI");
        tecno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecno1ActionPerformed(evt);
            }
        });

        tecno.add(tecno2);
        tecno2.setText("NO");

        extracontactual.add(extracontractual1);
        extracontractual1.setText("SI");

        extracontactual.add(extracontractual2);
        extracontractual2.setText("NO");

        uso_vehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOTOTAXI", "MENSAJERIA", "M.D TRANSPORTE", "OTRO" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(n_censo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fecha_censo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(fecha_de_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(n_recibo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(n_licencia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(o_transito, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(soat1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(soat2))
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tecno1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tecno2))
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(extracontractual1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(extracontractual2))
                                    .addComponent(jLabel20)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(v_pago)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(uso_vehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(linea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clase, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modelo)
                            .addComponent(n_motor)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(n_chasis)
                            .addComponent(cilindraje)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_censo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(fecha_censo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(linea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(n_motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(n_chasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel20))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n_licencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(o_transito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(soat1)
                        .addComponent(soat2)
                        .addComponent(tecno1)
                        .addComponent(tecno2)
                        .addComponent(extracontractual1)
                        .addComponent(extracontractual2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha_de_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(n_recibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(v_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(uso_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placaActionPerformed

    private void servicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servicioActionPerformed

    private void tecno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tecno1ActionPerformed
    
    public void setModel(ModeloVeiculo MV){
        cilindraje.setText(String.valueOf(MV.getCilindraje()));
        clase.setSelectedItem(MV.getClase());
        color.setText(MV.getColor());
        // esto viene de una consulta ajena: fecha_censo.setText(TOOL_TIP_TEXT_KEY);
        if(MV.getExtra().toUpperCase().equals("SI")){
            extracontractual1.setSelected(true);
            extracontractual2.setSelected(false);
        }else{
            extracontractual1.setSelected(false);
            extracontractual2.setSelected(true);
        }
        fecha_de_pago.setText(MV.getFecha_de_pago());
        linea.setText(MV.getLinea());
        marca.setText(MV.getMarca());
        modelo.setText(String.valueOf(MV.getModelo()));
        n_censo.setText(String.valueOf(MV.getNCenso()));
        n_chasis.setText(MV.getNChasis());
        n_licencia.setText(MV.getNLicencia());
        n_motor.setText(MV.getNMotor());
        n_recibo.setText(MV.getNRecibo());
        o_transito.setText(MV.getNTransito());
        observacion.setText(MV.getObservacion());
        placa.setText(MV.getPlaca());
        servicio.setSelectedItem(MV.getServicio());
        if(MV.getSoat().toUpperCase().equals("SI")){
            soat1.setSelected(true);
            soat2.setSelected(false);
        }else{
            soat1.setSelected(false);
            soat2.setSelected(true);
        }
        if(MV.getTecno().toUpperCase().equals("SI")){
            tecno1.setSelected(true);
            tecno2.setSelected(false);
        }else{
            tecno1.setSelected(false);
            tecno2.setSelected(true);
        }
        uso_vehiculo.setSelectedItem(MV.getUso());
        v_pago.setText(MV.getVPago());
    }
    
    public ModeloVeiculo getModel(){
        MV = new ModeloVeiculo();
        MV.setCilindraje(Long.parseLong(cilindraje.getText()));
        MV.setClase(String.valueOf(clase.getSelectedItem()));
        MV.setColor(color.getText());
        // esto viene de una consulta ajena: fecha_censo.setText(TOOL_TIP_TEXT_KEY);
        if(extracontractual1.isSelected()){
            MV.setExtra("SI");
        }else{
            MV.setExtra("NO");
        }
        MV.setFecha_de_pago(fecha_de_pago.getText());
        MV.setLinea(linea.getText());
        MV.setMarca(marca.getText());
        MV.setModelo(Long.parseLong(modelo.getText()));
        MV.setNCenso(Long.parseLong(n_censo.getText()));
        MV.setNChasis(n_chasis.getText());
        MV.setNLicencia(n_licencia.getText());
        MV.setNMotor(n_motor.getText());
        MV.setNRecibo(n_recibo.getText());
        MV.setNTransito(o_transito.getText());
        MV.setObservacion(observacion.getText());
        MV.setPlaca(placa.getText());
        MV.setServicio(servicio.getSelectedItem().toString());
        if(soat1.isSelected()){
            MV.setSoat("SI");
        }else{
            MV.setSoat("NO");
        }
        if(tecno1.isSelected()){
            MV.setTecno("SI");
        }else{
            MV.setTecno("NO");
        }
        MV.setUso(uso_vehiculo.getSelectedItem().toString());
        MV.setVPago(v_pago.getText());
        
        return MV;
    }
    
    public void setActive(){
        cilindraje.setEnabled(!cilindraje.isEnabled());
        clase.setEnabled(!clase.isEnabled());
        color.setEnabled(!color.isEnabled());
        extracontractual1.setEnabled(!extracontractual1.isEnabled());
        extracontractual2.setEnabled(!extracontractual2.isEnabled());
        fecha_censo.setEnabled(!fecha_censo.isEnabled());
        fecha_de_pago.setEnabled(!fecha_de_pago.isEnabled());
        jScrollPane1.setEnabled(!jScrollPane1.isEnabled());
        jSeparator1.setEnabled(!jSeparator1.isEnabled());
        linea.setEnabled(!linea.isEnabled());
        marca.setEnabled(!marca.isEnabled());
        modelo.setEnabled(!modelo.isEnabled());
        n_censo.setEnabled(!n_censo.isEnabled());
        n_chasis.setEnabled(!n_chasis.isEnabled());
        n_licencia.setEnabled(!n_licencia.isEnabled());
        n_motor.setEnabled(!n_motor.isEnabled());
        n_recibo.setEnabled(!n_recibo.isEnabled());
        o_transito.setEnabled(!o_transito.isEnabled());
        observacion.setEnabled(!observacion.isEnabled());
        placa.setEnabled(!placa.isEnabled());
        servicio.setEnabled(!servicio.isEnabled());
        soat1.setEnabled(!soat1.isEnabled());
        soat2.setEnabled(!soat2.isEnabled());
        tecno1.setEnabled(!tecno1.isEnabled());
        tecno2.setEnabled(!tecno2.isEnabled());
        uso_vehiculo.setEnabled(!uso_vehiculo.isEnabled());
        v_pago.setEnabled(!v_pago.isEnabled());
    }
    
    public void setActive(boolean estado){
        cilindraje.setEnabled(estado);
        clase.setEnabled(estado);
        color.setEnabled(estado);
        extracontractual1.setEnabled(estado);
        extracontractual2.setEnabled(estado);
        fecha_censo.setEnabled(estado);
        fecha_de_pago.setEnabled(estado);
        jScrollPane1.setEnabled(estado);
        jSeparator1.setEnabled(estado);
        linea.setEnabled(estado);
        marca.setEnabled(estado);
        modelo.setEnabled(estado);
        n_censo.setEnabled(estado);
        n_chasis.setEnabled(estado);
        n_licencia.setEnabled(estado);
        n_motor.setEnabled(estado);
        n_recibo.setEnabled(estado);
        o_transito.setEnabled(estado);
        observacion.setEnabled(estado);
        placa.setEnabled(estado);
        servicio.setEnabled(estado);
        soat1.setEnabled(estado);
        soat2.setEnabled(estado);
        tecno1.setEnabled(estado);
        tecno2.setEnabled(estado);
        uso_vehiculo.setEnabled(estado);
        v_pago.setEnabled(estado);
    }
    
    private ModeloVeiculo MV;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cilindraje;
    private javax.swing.JComboBox<String> clase;
    private javax.swing.JTextField color;
    private javax.swing.ButtonGroup extracontactual;
    private javax.swing.JRadioButton extracontractual1;
    private javax.swing.JRadioButton extracontractual2;
    private javax.swing.JFormattedTextField fecha_censo;
    private javax.swing.JTextField fecha_de_pago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField linea;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField modelo;
    private javax.swing.JFormattedTextField n_censo;
    private javax.swing.JTextField n_chasis;
    private javax.swing.JTextField n_licencia;
    private javax.swing.JTextField n_motor;
    private javax.swing.JTextField n_recibo;
    private javax.swing.JTextField o_transito;
    private javax.swing.JTextArea observacion;
    private javax.swing.JTextField placa;
    private javax.swing.JComboBox<String> servicio;
    private javax.swing.ButtonGroup soat;
    private javax.swing.JRadioButton soat1;
    private javax.swing.JRadioButton soat2;
    private javax.swing.ButtonGroup tecno;
    private javax.swing.JRadioButton tecno1;
    private javax.swing.JRadioButton tecno2;
    private javax.swing.JComboBox<String> uso_vehiculo;
    private javax.swing.JTextField v_pago;
    // End of variables declaration//GEN-END:variables
}
