/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package censo.views;

import java.awt.BorderLayout;
import java.awt.Toolkit;

/**
 *
 * @author GESTIONSAS
 */

public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public VentanaPrincipal() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    //break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        setLayout(new BorderLayout());
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 720));
        setMinimumSize(new java.awt.Dimension(1000, 720));
        setSize(new java.awt.Dimension(1000, 720));
        setResizable(false);
        
        Toolkit conf = Toolkit.getDefaultToolkit();
        
        int x = (conf.getScreenSize().width/2) - (getSize().width/2);
        int y = (conf.getScreenSize().height/2) - (getSize().height/2);
        
        setLocation(x, y);
        
        MenuBar = new javax.swing.JMenuBar();
        Menu1 = new javax.swing.JMenu();
        Menu2 = new javax.swing.JMenu();
        rc = new RompeCabezas(this);
        
        Menu1.setText("File");
        MenuBar.add(Menu1);

        Menu2.setText("Edit");
        MenuBar.add(Menu2);
        
        add(MenuBar, BorderLayout.NORTH);
        add(rc, BorderLayout.CENTER);
        
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1300, 700));
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setResizable(false);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    RompeCabezas rc;
    private javax.swing.JMenu Menu1;
    private javax.swing.JMenu Menu2;
    private javax.swing.JMenuBar MenuBar;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
